name: v2ray_push

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  timeout-minutes: 5

  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Push
        run: npm run start
        env:
          DB_URI: ${{ secrets.DB_URI }}
          SECRET: ${{ secrets.SECRET }}
          URL: ${{ secrets.URL }}
          WEBHOOK: ${{ secrets.WEBHOOK}}
