name: schedule

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Fetch
        run: npm run start
        env:
          DB_URI: ${{ secrets.DB_URI }}
          SECRET: ${{ secrets.SECRET }}
          WEBHOOK: ${{ secrets.WEBHOOK}}
          V2RAY_URL: ${{ secrets.V2RAY_URL }}
          SSR_URL: ${{ secrets.SSR_URL }}

      - name: Push commit
        run: chmod +x ./git-diff.sh && ./git-diff.sh
